### PR TITLE
Fixing the breaking changes to snabbdom API (the exports field) using TypeScript Path mapping

### PR DESCRIPTION
**Pull request by arashmilani**
It seems due to [changes the way snabbdom export](https://github.com/snabbdom/snabbdom/issues/726#issuecomment-656073726), and as the [TS does not support package exports yet](https://github.com/microsoft/TypeScript/issues/33079), we are going to use the [TypeScript path mapping ](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) for now to fix the issue.

This pull request has fixed above and the version number has been updated. Please publish the module to npm.

### CODE REVIEW

**Comment by arashmilani** [comment]
I have added another commit to resolve the path for babel so the test now can be run and pass.

**Comment by katyo** [comment]
I would like to setup travis-ci integration for this repo.

**Comment by katyo** [comment]
Please, rebase PR to current master

**Comment by arashmilani** [comment]
Rebased, Travis CI Build Passed and I think we are good to go.

**Comment by katyo** [comment]
Fine to hear. I will merge and publish it

**Comment by arashmilani** [comment]
Thank you.

**Pull request merged**
